### ISSUE TITLE
Include the openconfig-p4rt.yang in structs-0.go

### ISSUE THREAD

**Issue by rsindhujha** [openconfig/ondatra#12]
hi 
How do we include openconfig-p4rt.yang file while generating the below file ?
This has support of id and node-id for P4RT an will help push the OC config to DUT in Ondatra enviroment.

https://github.com/openconfig/ondatra/blob/f19ddc0acde622f9aa6a23fec5df53233c898682/telemetry/structs-0.go

**Comment by greg-dennis** [comment]
It needs to be part of an opensource repo to start. Is there a PR to add it to openconfig/public/release/models? Tagging @robshakir in case he has context for this.

**Comment by rsindhujha** [comment]
Yes openconfig-p4rt.yang is public release model -

https://github.com/openconfig/public/blob/master/release/models/p4rt/openconfig-p4rt.yang

**Comment by greg-dennis** [comment]
I'll take care of it.

**Comment by greg-dennis** [comment]
Done.
