### ISSUE TITLE
gNMI stat fetch failing for OTG nodes with latest Ondatra

### ISSUE THREAD

**Issue by biplamal** [openconfig/ondatra#13]
While trying to fetch any stat using latest ondatra from otg gnmi server getting following error
`gnmi.go:194: Get(t) at path origin:"openconfig" elem:{name:"interfaces"} elem:{name:"interface" key:{key:"name" value:"*"}} elem:{name:"ipv6-neighbors"} elem:{name:"ipv6-neighbor" key:{key:"ipv6-address" value:"*"}} elem:{name:"state"} elem:{name:"link-layer-address"} target:"ate": cannot subscribe to gNMI client: gnmi client getter not set on root object`

Also pasting the code snippet how we are trying to fetch.
`otg.Telemetry().InterfaceAny().Ipv6NeighborAny().LinkLayerAddress().Get(t)`

**Comment by greg-dennis** [comment]
Yes, I will be pushing out a change that addresses this and expanding the kne_bind integration test

**Comment by greg-dennis** [comment]
This should be fixed now, thanks!
