### ISSUE TITLE
Logging for GNMI.GetRequest

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#15]
Thanks for adding the support for GNMI Get for config nodes. The current logging (https://github.com/openconfig/ondatra/blob/be319f7ae58d392f3514aeeed273b3b0585bed2f/internal/gnmigen/genutil/genutil.go#L890) is a little confusing since it shows a subscribe message is sent with  encoding as PROTO which is not right.  Can you please move the logging before sending the get request https://github.com/openconfig/ondatra/blob/be319f7ae58d392f3514aeeed273b3b0585bed2f/internal/gnmigen/genutil/genutil.go#L814 ,i.e., 
```
	log.V(1).Info(prototext.Format(getReq))
	resp, err := gs.client.Get(gs.ctx, getReq)

```

**Comment by greg-dennis** [comment]
This will be fixed or improved in the next two weeks.

**Comment by greg-dennis** [comment]
Ok, was actually fixed today!

**Comment by mojiiba** [comment]
Thanks a lot!
