### ISSUE TITLE
Remove null value from ixconfig generated traffic config

### ISSUE THREAD

**Issue by alakendu** [openconfig/ondatra#19]
Marshal of ixconfig is creating xpath contain null / black array value 
```json
{
   "xpath": "/traffic/trafficItem[1]/configElement[1]/stack[@alias = 'ipv4-2']/field[@alias = 'ipv4.header.version-1']",
   "valueList": []
},
{
   "xpath": "/traffic/trafficItem[1]/configElement[1]/stack[@alias = 'ipv4-2']/field[@alias = 'ipv4.header.headerLength-2']",
   "valueList": []
}
```
It will create huge unnecessary entry for large configuration which will add more performance overhead. So, it will better to remove those null value from traffic config.

**Comment by jasdeep-hundal** [comment]
I will be looking into this.

**Comment by jasdeep-hundal** [comment]
Fixed in https://github.com/openconfig/ondatra/commit/d3150ccf2cbcb92f770c1bb269d635c81038eab5
