### ISSUE TITLE
Feature request - need a way to set test timeout value from within a test

### ISSUE THREAD

**Issue by sgirishj** [openconfig/ondatra#21]
Hi, I am looking to set the RunTime timeout value for a test to something other than the default value of 10 minutes. Is there a way to set it from within the featureprofiles testcase and pass it through fptest.RunTests() to ondatra.RunTests() or set it as a flag inside the test? Had originally reported this under featureprofiles repo: https://github.com/openconfig/featureprofiles/issues/202

Thanks!

PS: I have used the parameter '-run_time' to set a desired timeout value when executing a test from the command line. Looking for something that I could set within the Ondatra test itself, so the user of the test does not need to worry about it when executing.

**Comment by greg-dennis** [comment]
@sgirishj, sorry for being delinquent in responding to this feature request. is this still something you find nice to have? Would using the go test `-timeout` flag ([doc](https://pkg.go.dev/cmd/go/internal/test)) satisfy your use case?

**Comment by sgirishj** [comment]
No problem @greg-dennis, thanks for getting back! I have been using the -timeout flag. I think it would still be a useful feature to have - that way, the user of the test does not have to remember to pass the timeout flag when executing the test. Would come in handy especially when the runtimes vary quite widely across the tests within Featureprofiles, for example. The developer of the test has insight into a test's approximate run time and can set this timeout value from within the test. If a user ends up providing the -timeout flag during runtime, that value could overwrite what the test contains. Thanks!

**Comment by greg-dennis** [comment]
@sgirishj This was a thoughtful and thought-provoking request, but as of right now, I have decided to close this without taking any action on it. The rationale:

1. The featureprofiles team hasn't expressed any interest in utilizing or allowing this feature in the tests they open source. So as a practical matter, it's unclear whether you would actually be able to make use of it.

2. It would also be of non-trivial maintenance burden to maintain these timeouts, particularly as the test grow and evolve.

3. Go is planning to add its own per-test timeout feature that might make this superfluous: https://github.com/golang/go/issues/48157

4. There has been some discussion of moving to Bazel for OpenConfig and Ondatra builds at some point. If that were pursued, Bazel has its own mechanism for setting timeouts on test targets.

So no action at this time, but I wouldn't rule out it cropping up again in a context which requires some form of implementation. Thanks!

**Comment by sgirishj** [comment]
> @sgirishj This was a thoughtful and thought-provoking request, but as of right now, I have decided to close this without taking any action on it. The rationale:
> 
> 1. The featureprofiles team hasn't expressed any interest in utilizing or allowing this feature in the tests they open source. So as a practical matter, it's unclear whether you would actually be able to make use of it.
> 2. It would also be of non-trivial maintenance burden to maintain these timeouts, particularly as the test grow and evolve.
> 3. Go is planning to add its own per-test timeout feature that might make this superfluous: [cmd/go: add per-test timeouts golang/go#48157](https://github.com/golang/go/issues/48157)
> 4. There has been some discussion of moving to Bazel for OpenConfig and Ondatra builds at some point. If that were pursued, Bazel has its own mechanism for setting timeouts on test targets.
> 
> So no action at this time, but I wouldn't rule out it cropping up again in a context which requires some form of implementation. Thanks!

Ack @greg-dennis, thanks!
