### ISSUE TITLE
APIs for openconfig-if-ethernet-ext.yang model is missing

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#33]
Hi, Could you please add the support for openconfig-if-ethernet-ext.yang (https://github.com/openconfig/public/blob/master/release/models/interfaces/openconfig-if-ethernet-ext.yang).

Thanks
Moji

**Comment by greg-dennis** [comment]
Will be fixed soon.

**Comment by greg-dennis** [comment]
Fixed.
