### ISSUE TITLE
Need ATE API to set license server

### ISSUE THREAD

**Issue by sgirishj** [openconfig/ondatra#37]
Hi, this request is to add support for reading the ATE license server IP from the Ondatra binding file and configuring it at run time through an ATE API.

Thanks!

**Comment by greg-dennis** [comment]
Why do you need to change licensing at runtime?

**Comment by sgirishj** [comment]
Not really to change at run time. Currently when a virtual topology is launched, the license server needs to be configured manually by going into the web ui once the ATE is up. This manual step coudl be avoided if it could be done through an API instead.

Thanks!

**Comment by greg-dennis** [comment]
I don't think there should or needs to be a test API for this. Doubtful we would ever see a vendor-neutral API for licenses. Instead, there should be some way to either configure the desired licenses in the topology or have them automatically determined for you.

**Comment by greg-dennis** [comment]
@sgirishj, are you referring to the IxNetwork web UI? What is the ATE in your case?

**Comment by sgirishj** [comment]
Yes Greg, its the IxNetwork web UI. ATE is Keysight Ixia. Thanks!

**Comment by greg-dennis** [comment]
@sgirishj, why do you have to reconfigure it every time? We configure our licenses once on the chassis host and we're done. Are you deploying IxNetwork in a docker container?

**Comment by sgirishj** [comment]
Its a one time configuration thats done per virtual topology launch. Not needed every time a script is run on the topology. Would be optimal to have it automated/included as part of the topology launch sequence though. Thanks!

**Comment by greg-dennis** [comment]
@sgirishj, yes but where is your IxNetwork running?

**Comment by sgirishj** [comment]
It runs in a virtual chassis (a VM). Thanks!

**Comment by greg-dennis** [comment]
I'm going to close this issue, because it should be solved in the VM configuration before you launch the topology, not at runtime. I have directed some Keysight engineers to this Issue so they might provide you the appropriate instructions for doing so.
