### ISSUE TITLE
Feature request - need a way to retrieve ISIS Learned info in ATE

### ISSUE THREAD

**Issue by Vibaswan** [openconfig/ondatra#42]
Use-case: ISIS feature profile tests would be needing ISIS metrics which would in turn, would require to get some learned info of the ISIS LSPS

So currently I see there are ways we can fetch Isis metrics like the below snippet:

```go
isis := at.NetworkInstance(ap.Name()).Protocol(telemetry.PolicyTypes_INSTALL_PROTOCOL_TYPE_ISIS, fmt.Sprintf("isis-%s", ap.Name())).Isis()
isis.LevelAny().LspAny().IsType().Get(t)
isis.LevelAny().LspAny().Flags().Get(t)
isis.LevelAny().LspAny().LspId().Get(t)
```
But they return empty results.
So I guess we need to populate these with the result fetched from ATE .

I see a similar effort was done for `BGP` in the following files
https://github.com/openconfig/ondatra/blob/main/internal/ixgnmi/ixgnmi.go
https://github.com/openconfig/ondatra/blob/main/internal/ixgnmi/learnedinfo.go

Probably would be needing similar kind of support for ISIS as well.

Please let me know If I have missed something

**Comment by greg-dennis** [comment]
I am evaluating this request this sprint and will have either completed this request or will have a timetable to announce by 10/25.

**Comment by greg-dennis** [comment]
@Vibaswan can you please provide an IxNetwork config and reference to the IxNetwork operation that retrieves the specific info you are interested in?

**Comment by greg-dennis** [comment]
Here is a sample table of information I received from the ISIS learned info:

|  name                    | value            |
| ------------------------ | ---------------- |
|  Learned Via             | L2               |
|  Learned From            | <empty>          |
|  Metric                  | 30               |
|  IPv4 Prefix             | 72.16.1.0        |
|  Mask                    | 30               |
|  PPrefix Attribute Flags | <empty>          |
|  IPv4 Source Router ID   | <empty>          |
|  IPv6 Source Router ID   | <empty>          |
|  SID/Label               | <empty>          |
|  Algorithm               | <empty>          |
|  FAPM Metric             | <empty>          |
|  System ID               | 1 11 11 11 11 11 |
|  Pseudo Node Index       | 0                |
|  LSP Index               | 0                |
|  Host Name               | xx07.sql17       |
|  Sequence Number         | 3                |
|  Age (in secs)           | 32               |

Does this contain everything of interest?

**Comment by greg-dennis** [comment]
@Vibaswan, for this example, I am inferring that both the level number and is-type is 2, that the LSP ID is "1111.1111.1111.00-00", the sequence number is 3, and the flags are an empty list. Do you know how I trigger some flag attributes to be learned?

**Comment by Vibaswan** [comment]
Hi @greg-dennis , 
Currently we are on Holiday, will get back to you by the end of the week

**Comment by Vibaswan** [comment]
Hi @greg-dennis,

The test script which I shared for you is just a sample to retrieve learned info from ISIS router. This requirement has come from @cprabha of Juniper and in future there might be other fields  that may be needed by the WBB test cases. @cprabha would you please comment if the given table of contents (provided in the earlier comments by @greg-dennis ) would suffice your need (apart from overload bit, as this is not present in current IxNetwork ISIS router)

**Comment by cprabha** [comment]
@Vibaswan , @greg-dennis 
As Per gnmi1.3 testcase details we need verify overload bit and metric on ATE for ISIS sessions.

**Comment by greg-dennis** [comment]
The latest Ondatra commit now provides some basic support for gathering ISIS LSPs through gNMI. It provides the LSP ID, IS type/level, and sequence number. Please note that the network instance value for both ISIS and BGP must be the name of the _interface_ created when using the Ondatra `AddInterface` function, and the id of the protocol is always "0". Please give it a try and I will let you know when flags is done.

**Comment by cprabha** [comment]
Thanks Greg, I will check and update you.

**Comment by greg-dennis** [comment]
I tried the suggestion configuration but couldn't get Ixia to render flags in the learned info. I'm tempted to mark this fixed and let either of you @Vibaswan or @cprabha augment the inference now that the structure for it is in place:
https://github.com/openconfig/ondatra/blob/main/internal/ixgnmi/isislsdb.go#L106

Now that the basic structure is in place, do you think you could submit PRs for whatever additional information you want rendered in the telemetry?

**Comment by cprabha** [comment]
Hi Vibaswan,

Please could you help to verify this fix.

Thanks,
Prabha



Juniper Business Use Only

**Comment by Vibaswan** [comment]
yes I could fetch the sequence number and istype using the new ondatra release also could see the learned info is being triggered at IxNetwork side

**Comment by greg-dennis** [comment]
I am going to mark this fixed then. The code has been significantly refactored to make adding new gnmi from learned info fairly straightforward. Please submit PRs for any additional gnmi needed from learned info or reach out to me with any difficulties you have doing that.

**Comment by cprabha** [comment]
Thanks Greg, Vibaswan.
