### ISSUE TITLE
ATE : Invalid IP address during ISIS config in ATE

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [openconfig/ondatra#46]
ATE Topology push results in Error: " Invalid IP address"

The issue is because of the "rtrcapId" is empty string as shown in below snap while ixNetwork expects an address of format IPv4.

![image](https://user-images.githubusercontent.com/48308607/197971717-c515ee47-4786-41f0-99b2-543ad128aa2e.png)

![image](https://user-images.githubusercontent.com/48308607/197971870-72835096-910d-44fe-ad22-0c89153f458f.png)

**Comment by greg-dennis** [comment]
Fix merged in latest commit
