### ISSUE TITLE
Feature Request : BGP AS Path info retrieval from BGP RIB

### ISSUE THREAD

**Issue by cprabha** [openconfig/ondatra#48]
Hi,

Please provide support to retrieve BGP AS Path info from BGP RIB details.

rib := at.NetworkInstance(ap.Name()).Protocol(telemetry.PolicyTypes_INSTALL_PROTOCOL_TYPE_BGP, fmt.Sprintf("bgp-%s", ap.Name())).Bgp().Rib()
			pref := rib.AfiSafi(telemetry.BgpTypes_AFI_SAFI_TYPE_IPV4_UNICAST).Ipv4Unicast().
				Neighbor(setup.DutIPPool[ap.ID()].String()).AdjRibInPre().RouteAnyPrefix(0).Prefix().Get(t)
			asPath := rib.AttrSetAny().    ================> We need  As path option here to retrieve AS Path info.

Thanks,
Prabha

**Comment by greg-dennis** [comment]
@cprabha, looks like a dupe of https://github.com/openconfig/ondatra/issues/45 ?

**Comment by cprabha** [comment]
@greg-dennis , sorry some reason I could not see the old issue , closing it now.
