### ISSUE TITLE
Question about implemenation of gnmi subscription in ondatra

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#49]
Hi, I have a  question regarding sending closeSend [here](https://github.com/openconfig/ondatra/blob/10c91da9d0d7c3177b6ffe94d39a14667264d807/internal/gnmigen/genutil/genutil.go#L855) in ondatra code. It seems when the client sends closeSend, the server can send an EOF and close the stream. 
``` 
type ServerStream

	// RecvMsg blocks until it receives a message into m or the stream is
	// done. It returns io.EOF when the client has performed a CloseSend. On
	// any non-EOF error, the stream is aborted and the error contains the
	// RPC status.
	//
	// It is safe to have a goroutine calling SendMsg and another goroutine
	// calling RecvMsg on the same stream at the same time, but it is not
	// safe to call RecvMsg on the same stream in different goroutines.
	RecvMsg(m interface{}) error
...

```

if my understanding is correct, this can result in failure of the streaming call on ondatra side. Indeed we see some EOF issues for streaming requests that get resolved by commenting this line [here](https://github.com/openconfig/ondatra/blob/10c91da9d0d7c3177b6ffe94d39a14667264d807/internal/gnmigen/genutil/genutil.go#L855). Can u please help me to understand why ondatra sends closesend before finishing receiving data.

Thanks

**Comment by greg-dennis** [comment]
Where did you find a contract/documentation for `CloseSend` that says the server is to close the stream? The documentation says that it [closes the _send_ direction of the stream](https://pkg.go.dev/google.golang.org/grpc#ClientStream), not the receive direction. A server that stops sending messages on CloseSend is buggy. There is some more clarification here:
https://github.com/grpc/grpc-go/issues/2015#issuecomment-382958126

**Comment by mojiiba** [comment]
Thanks a lot for the prompt response. I was very helpful!
