### ISSUE TITLE
Entity-Id leaf on oc-platform not found using ondatra

### ISSUE THREAD

**Issue by sahubbal-cisco** [openconfig/ondatra#53]
The below path is not found on ondatra under the openconfig-platform model:
“/components/component/state/oc-platform-ext:entity-id”
 
Due to this when get is done at the component container level we see an unmarshall error at entity-id.
The gNMI subscribe req:
subscribe: {
prefix: {
target: "DUT"
}
subscription: {
path: {
origin: "openconfig"
elem: {
name: "components"
}
elem: {
name: "component"
key: {
key: "name"
value: "0/0/CPU0-QSFP_DD Optics Port 35"
}
}
}
}
mode: ONCE
encoding: PROTO
}
 

 
I1109 10:01:12.385033 777 genutil.go:992] Received gNMI SyncResponse.
I1109 10:01:12.389044 777 schema_helpers.go:53] noncompliant data encountered while unmarshalling: Noncompliance Errors by category:
Path Noncompliance Errors:
Unmarshal uint_val:8528 into origin:"openconfig" elem:{name:"components"} elem:{name:"component" key:{key:"name" value:"0/0/CPU0-QSFP_DD Optics Port 35"}} elem:{name:"state"} elem:{name:"entity-id"}: rpc error: code = InvalidArgument desc = no match found in *telemetry.Component, for path elem:{name:"state"} elem:{name:"entity-id"}
Type Noncompliance Errors: None
Value Restriction Noncompliance Errors: None
 

 
 
The entity-id has not been added recently according to https://github.com/openconfig/public/blob/624655d053ad1fdda62901c7e2055c22cd5d6a05/release/models/platform/openconfig-platform-ext.yang

**Comment by greg-dennis** [comment]
This is just a matter of our adding an additional yang file to the inputs of the telemetry API generation. I'll do today.

**Comment by greg-dennis** [comment]
An update for this has just been merged.
