### ISSUE TITLE
Test breakage because of error messages annotation

### ISSUE THREAD

**Issue by mojiiba** [openconfig/ondatra#56]
Hi, 
This function (https://github.com/openconfig/ondatra/blob/89ea1ae2f3284530e65586cf86a9846d92782516/internal/rawapis/intercept.go#L68), annotates the error messages, but it also removes the error details that results in failure for fp tests that check rpc error details (e.g., TE-6.2 and TE-15.1).  Appreciate if we can have a quick fix for this since it breaks tests in our nighty run.

Thanks
Moji

**Comment by greg-dennis** [comment]
@mojiiba, could you offer repro instructions or be specific about what you mean by "error details"? There are unit tests that check it is preserving the content of the original error. Is there logic somewhere that is very sensitive to the specific format of the error message?

**Comment by mojiiba** [comment]
yes, there are three test cases that checks the details of error messages. Here is one of them:
https://github.com/openconfig/gribigo/blob/d26b0f6d75e4e3939a5766717ae262fc57b03eff/compliance/flush.go#L124

To repro this, you need to run https://github.com/openconfig/featureprofiles/blob/main/feature/gribi/ate_tests/gribigo_compliance_test/gribigo_compliance_test.go 

to give you more info the expected error message for this test is: 
`
2022/12/01 22:55:21 http2: decoded hpack field header field ":status" = "200"
2022/12/01 22:55:21 http2: decoded hpack field header field "content-type" = "application/grpc"
2022/12/01 22:55:21 http2: decoded hpack field header field "grpc-status" = "3"
2022/12/01 22:55:21 http2: decoded hpack field header field "grpc-message" = "unspecified network instance"
2022/12/01 22:55:21 http2: decoded hpack field header field "grpc-status-details-bin" = "CAMSHHVuc3BlY2lmaWVkIG5ldHdvcmsgaW5zdGFuY2UaMgosdHlwZS5nb29nbGVhcGlzLmNvbS9ncmliaS5GbHVzaFJlc3BvbnNlRXJyb3ISAggG" `

but when this error message is annotated, the details is somehow dropped and causes failure for tests. When I  disable the annotation or run the test without ondatra, the test can pass.

**Comment by greg-dennis** [comment]
While I'm figuring this out, I will proceed with removing this interceptor for the time being.

**Comment by mojiiba** [comment]
thanks a lot for the prompt action!

**Comment by greg-dennis** [comment]
The Ondatra commit just now removes the interceptor entirely until I figure out what's going on. I still want to update featureprofiles to this commit.

**Comment by mojiiba** [comment]
thanks a lot!

**Comment by greg-dennis** [comment]
The test error annotation feature has been re-enabled with a fix to ensure the grpc error details are not dropped.
