### ISSUE TITLE
Data type mismatch error while running scripts : "invalid type ptr in leaflist"

### ISSUE THREAD

**Issue by cprabha** [openconfig/ondatra#59]
Error from script:

{{NetworkInstance_Protocol_Bgp_Rib_AfiSafi_Ipv6Unicast_Neighbor_AdjRibInPre_Route true 0xc004f2f800 0x9960a80 0x9960b60 0xc0037901c0 true}}: error receiving gNMI response: failed to render notifications: cannot represent field value [0xc000566b00] as TypedValue for path /network-instances/network-instance[name=port2]/protocols/protocol[identifier=BGP][name=0]/bgp/rib/attr-sets/attr-set[index=0]/as-path/as-segment: invalid type ptr in leaflist

Path :

 path /network-instances/network-instance[name=port2]/protocols/protocol[identifier=BGP][name=0]/bgp/rib/attr-sets/attr-set[index=0]/as-path/as-segment

Snapshot on Ixia showing received routes:

<img width="726" alt="data_type_error" src="https://user-images.githubusercontent.com/29638902/207440715-e3c2c00c-ce8d-4376-a5bd-2462cf4f5693.png">

Error verbose details:

I1213 12:18:13.123988 1232102 gnmi.go:91] subscribe: {
  prefix: {
    target: "10.52.56.56"
  }
  subscription: {
    path: {
      origin: "openconfig"
      elem: {
        name: "network-instances"
      }
      elem: {
        name: "network-instance"
        key: {
          key: "name"
          value: "port2"
        }
      }
      elem: {
        name: "protocols"
      }
      elem: {
        name: "protocol"
        key: {
          key: "identifier"
          value: "BGP"
        }
        key: {
          key: "name"
          value: "65538"
        }
      }
      elem: {
        name: "bgp"
      }
      elem: {
        name: "rib"
      }
      elem: {
        name: "afi-safis"
      }
      elem: {
        name: "afi-safi"
        key: {
          key: "afi-safi-name"
          value: "IPV6_UNICAST"
        }
      }
      elem: {
        name: "ipv6-unicast"
      }
      elem: {
        name: "neighbors"
      }
      elem: {
        name: "neighbor"
        key: {
          key: "neighbor-address"
          value: "2001:db8::5"
        }
      }
      elem: {
        name: "adj-rib-in-pre"
      }
      elem: {
        name: "routes"
      }
      elem: {
        name: "route"
        key: {
          key: "path-id"
          value: "0"
        }
        key: {
          key: "prefix"
          value: "2001:db8:1::1/128"
        }
      }
      elem: {
        name: "state"
      }
      elem: {
        name: "attr-index"
      }
    }
  }
  encoding: PROTO
}
I1213 12:18:13.131366 1232102 subscribe.go:268] peer: [::1]:49520 target: "10.52.56.56" subscription: subscribe:{prefix:{origin:"openconfig" target:"10.52.56.56"} subscription:{path:{elem:{name:"network-instances"} elem:{name:"network-instance" key:{key:"name" value:"port2"}} elem:{name:"protocols"} elem:{name:"protocol" key:{key:"identifier" value:"BGP"} key:{key:"name" value:"65538"}} elem:{name:"bgp"} elem:{name:"rib"} elem:{name:"afi-safis"} elem:{name:"afi-safi" key:{key:"afi-safi-name" value:"IPV6_UNICAST"}} elem:{name:"ipv6-unicast"} elem:{name:"neighbors"} elem:{name:"neighbor" key:{key:"neighbor-address" value:"2001:db8::5"}} elem:{name:"adj-rib-in-pre"} elem:{name:"routes"} elem:{name:"route" key:{key:"path-id" value:"0"} key:{key:"prefix" value:"2001:db8:1::1/128"}} elem:{name:"state"} elem:{name:"attr-index"}}} encoding:PROTO}
I1213 12:18:13.131952 1232102 subscribe.go:391] start processSubscription for 0xc0048fb9f0
I1213 12:18:13.132040 1232102 subscribe.go:399] end processSubscription for 0xc0048fb9f0
I1213 12:18:13.232415 1232102 ixweb.go:235] Response to "/api/v1/sessions/16/ixnetwork/operations/select": "{\"id\":\"\",\"url\":\"\",\"resultUrl\":\"\",\"executionTimeMs\":33.0,\"state\":\"SUCCESS\",\"progress\":100,\"message\":null,\"result\":[{\"href\":\"/api/v1/sessions/16/ixnetwork\",\"xpath\":\"/\",\"topology\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/1\",\"id\":1,\"xpath\":\"/topology[1]\",\"deviceGroup\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/1/deviceGroup/1\",\"id\":1,\"xpath\":\"/topology[1]/deviceGroup[1]\",\"ethernet\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/1/deviceGroup/1/ethernet/1\",\"id\":1,\"xpath\":\"/topology[1]/deviceGroup[1]/ethernet[1]\",\"ipv6\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/1/deviceGroup/1/ethernet/1/ipv6/1\",\"id\":1,\"xpath\":\"/topology[1]/deviceGroup[1]/ethernet[1]/ipv6[1]\",\"bgpIpv6Peer\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/1/deviceGroup/1/ethernet/1/ipv6/1/bgpIpv6Peer/1\",\"id\":1,\"xpath\":\"/topology[1]/deviceGroup[1]/ethernet[1]/ipv6[1]/bgpIpv6Peer[1]\"}]}]}]}]},{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2\",\"id\":2,\"xpath\":\"/topology[2]\",\"deviceGroup\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1\",\"id\":1,\"xpath\":\"/topology[2]/deviceGroup[1]\",\"ethernet\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1\",\"id\":1,\"xpath\":\"/topology[2]/deviceGroup[1]/ethernet[1]\",\"ipv6\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1/ipv6/1\",\"id\":1,\"xpath\":\"/topology[2]/deviceGroup[1]/ethernet[1]/ipv6[1]\",\"bgpIpv6Peer\":[{\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1/ipv6/1/bgpIpv6Peer/1\",\"id\":1,\"xpath\":\"/topology[2]/deviceGroup[1]/ethernet[1]/ipv6[1]/bgpIpv6Peer[1]\"}]}]}]}]}]}]}"
I1213 12:18:13.393212 1232102 ixweb.go:235] Response to "/api/v1/sessions/16/ixnetwork/topology/deviceGroup/ethernet/ipv6/bgpIpv6Peer/operations/getAllLearnedInfo": "{\"id\":\"\",\"url\":\"\",\"resultUrl\":\"\",\"executionTimeMs\":72.0,\"state\":\"SUCCESS\",\"progress\":100,\"message\":null,\"result\":\"kVoid\"}"
I1213 12:18:13.582134 1232102 ixweb.go:235] Response to "/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1/ipv6/1/bgpIpv6Peer/1/learnedInfo/1/table/1": "{\"id\":1,\"type\":\"IPv6 Prefixes 1\",\"columns\":[\"IPv6 Prefix\",\"Prefix Length\",\"Path ID\",\"IPv4 Next Hop\",\"IPv6 Next Hop\",\"IPv6 Next Hop 2\",\"MED\",\"Local Preference\",\"Origin\",\"AS Path\",\"Community\",\"AIGP\",\"Color\",\"Large Community\",\"SRv6 SID\",\"Locator Block Length\",\"Locator Node Length\",\"Function Length\",\"Argument Length\"],\"values\":[[\"2001:db8:1::1\",\"128\",\"NA\",\"removePacket[ ]\",\"2001:db8::5\",\"fe80::ba2a:d1ff:fe27:18\",\"0\",\"0\",\"IGP\",\"<65537 65536>\",\" \",\"\",\"\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\"],[\"2001:db8:1::2\",\"128\",\"NA\",\"removePacket[ ]\",\"2001:db8::5\",\"fe80::ba2a:d1ff:fe27:18\",\"0\",\"0\",\"IGP\",\"<65537 65536>\",\" \",\"\",\"\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\"],[\"2001:db8:1::3\",\"128\",\"NA\",\"removePacket[ ]\",\"2001:db8::5\",\"fe80::ba2a:d1ff:fe27:18\",\"0\",\"0\",\"IGP\",\"<65537 65536>\",\" \",\"\",\"\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\"],[\"2001:db8:1::4\",\"128\",\"NA\",\"removePacket[ ]\",\"2001:db8::5\",\"fe80::ba2a:d1ff:fe27:18\",\"0\",\"0\",\"IGP\",\"<65537 65536>\",\" \",\"\",\"\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\",\"NA\"]],\"actions\":[],\"rowCount\":4,\"links\":[{\"rel\":\"self\",\"method\":\"GET\",\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1/ipv6/1/bgpIpv6Peer/1/learnedInfo/1/table/1\"},{\"rel\":\"meta\",\"method\":\"OPTIONS\",\"href\":\"/api/v1/sessions/16/ixnetwork/topology/2/deviceGroup/1/ethernet/1/ipv6/1/bgpIpv6Peer/1/learnedInfo/1/table/1\"}]}"
    route_propagation_test.go:330: Await(t) on ate(10.52.56.56) at &{{NetworkInstance_Protocol_Bgp_Rib_AfiSafi_Ipv6Unicast_Neighbor_AdjRibInPre_Route true 0xc004f2f800 0x9960a80 0x9960b60 0xc0037901c0 true}}: error receiving gNMI response: failed to render notifications: cannot represent field value [0xc000566b00] as TypedValue for path /network-instances/network-instance[name=port2]/protocols/protocol[identifier=BGP][name=0]/bgp/rib/attr-sets/attr-set[index=0]/as-path/as-segment: invalid type ptr in leaflist

Thanks,
Prabha

**Comment by cprabha** [comment]
ref: https://github.com/openconfig/ondatra/issues/57

**Comment by greg-dennis** [comment]
@cprabha, in https://github.com/openconfig/ondatra/issues/57, I thought you said this specific error went away by syncing to the latest Ondatra. If so, that's what https://github.com/openconfig/ondatra/issues/57 was about and it has been fixed. There still won't be AS path segments yet, because we are _still_ waiting for this to be merged into OpenConfig, which is happening in two days: https://github.com/openconfig/public/pull/750#issuecomment-1334429655

**Comment by cprabha** [comment]
@greg-dennis , specific error went away with older ondatra repo but check was still failing.
workaround did not make script to pass , even though we had routes on ATE.
If we get #750 in 2 days, then will wait for it.

Thanks,.
Prabha.

**Comment by cprabha** [comment]
Hi Greg,

Script passes with latest ondatra repo and protocol name fix as in "https://github.com/openconfig/featureprofiles/pull/916"

Thanks,
Prabha
