### ISSUE TITLE
delay issue when validating data with gnmi.GetAll/CollectAll 

### ISSUE THREAD

**Issue by fxz101** [openconfig/ondatra#66]
After switching from device.Telemetry().NetworkInstanceAny().Afts().Ipv4EntryAny().Collect(t, subscriptionDuration).Await(t) to gnmi.CollectAll(t, device, gnmi.OC().NetworkInstanceAny().Afts().Ipv4EntryAny().State(),subscriptionDuration).Await(t) , we are seeing larger delay when trying to get 60k ipv4 prefixes. It took forever for backend to validate the data. That step stuck more then 30 minutes.  We did not experience same delay with older lib.

**Comment by greg-dennis** [comment]
Can you please produce an Ondatra test that demonstrates the regression?

**Comment by DanG100** [comment]
We were able to repro this. Can try with ygnmi v0.7.5 and check if the issue is solved?

**Comment by fxz101** [comment]
thx, will try that when FeatureProfiles move to 0.7.5.  currently it's in 0.7.4
