### ISSUE TITLE
support needed to get RouteAnyPrefix() leaf and AsPath() leaves for BGP Rib

### ISSUE THREAD

**Issue by cprabha** [openconfig/ondatra#67]
Hi,

I have to get AsPath for all the prefixes in rib .  Below is not supported, please could you check,
I have highglighed unsupported leaf in bold.

rib := at.NetworkInstance(ap.Name()).Protocol(oc.PolicyTypes_INSTALL_PROTOCOL_TYPE_BGP, fmt.Sprintf("bgp-%s", ap.Name())).Bgp().Rib()
			prefixPath := rib.AfiSafi(oc.BgpTypes_AFI_SAFI_TYPE_IPV4_UNICAST).Ipv4Unicast().
				Neighbor(setup.DUTIPList[ap.ID()].String()).AdjRibInPre().**RouteAnyPrefix**(0).Prefix()
			pref := gnmi.Get(t, dut, prefixPath.State())
			asPath := gnmi.Get(t, dut, rib.AttrSetAny().**AsPath()**.State())
			

Thanks,
Prabha

**Comment by greg-dennis** [comment]
@cprabha, what do you mean by `RouteAnyPrefix(0).Prefix()`? The Route list has three keys: path-id, endpoint, and color. Is the 0 meant to be a path-id and you want to a wildcard for the endpoint and color? If so, that would be available as `AdjRibInPre().RouteAny().WithPathId(0).Prefix()`

**Comment by cprabha** [comment]
Thanks Greg,
It worked fine with AdjRibInPre().RouteAny().WithPathId(0).Prefix() and AttrSetAny().AsSegmentAny().

**Comment by cprabha** [comment]
@greg-dennis , 
asPath := gnmi.GetAll(t, ate, rib.AttrSetAny().AsSegmentAny().State())  ==> this is returning pointer instead of  value .
Can you please check ?

Output 
=====
asPath
[]*github.com/openconfig/ondatra/gnmi/oc.NetworkInstance_Protocol_Bgp_Rib_AttrSet_AsSegment len: 200, cap: 200, [*{Index: *0, Member: []uint32 len: 5, cap: 8, [64500,64500,64500,64500,64502], Type: RibBgp_AsPathSegmentType_AS_SEQ (1)},*{Index: *0, Member: ...
[0..99]:
[0]: *github.com/openconfig/ondatra/gnmi/oc.NetworkInstance_Protocol_Bgp_Rib_AttrSet_AsSegment {Index: *0, Member: []uint32 len: 5, cap: 8, [64500,64500,64500,64500,64502], Type: RibBgp_AsPathSegmentType_AS_SEQ (1)}
[1]: *github.com/openconfig/ondatra/gnmi/oc.NetworkInstance_Protocol_Bgp_Rib_AttrSet_AsSegment {Index: *0, Member: []uint32 len: 5, cap: 8, [64500,64500,64500,64500,64502], Type: RibBgp_AsPathSegmentType_AS_SEQ (1)}


Thanks,
Prabha

**Comment by greg-dennis** [comment]
@cprabha, GetAll is returning a list of all the segments, which should be expected. Does that make sense?

**Comment by cprabha** [comment]
got it, Thanks Greg.
