### ISSUE TITLE
No option available to set media type in ATE

### ISSUE THREAD

**Issue by r4huluk** [openconfig/ondatra#73]
Currently there is no option available to set media type (copper/fiber) for ATE ports. Some card models in Ixia that supports `Fiber` or `Copper` connections on the same port (e.g. NOVUS10/1GE16DP) defaults to media type `Copper`. When physical topology is built with fiber connections on such Ixia cards, running ondatra scripts require setting a breakpoint after loading the ATE topology and manually changing the media type in IxNetwork Web UI.

**Comment by greg-dennis** [comment]
We're placing a high priority on migrating all traffic automation from IxNetwork to OTG and haven't budgeted any time to work on IxNetwork feature requests. However, we do accept and will review PRs to add new features. Do you have a similar issue with OTG?

**Comment by greg-dennis** [comment]
@r4huluk, then we'd probably just focus on getting the OTG test running successfully and delete the ATE version. If you want the ATE version sooner, I'd be happy to review a PR.
