### ISSUE TITLE
issue seen while configuring Level 1 and 2 together in ATE

### ISSUE THREAD

**Issue by pallavid1008** [openconfig/ondatra#77]
I am trying to configure ISIS level 1 and level 2 for one port in ATE. But I am observing the level is getting overwritten with the later value.
How can I combine level1+2 in the code.

Below is the code I am using:
 
func configureATE(t *testing.T, ate *ondatra.ATEDevice) *ondatra.ATETopology {
    topo := ate.Topology().New()
 
    port1 := ate.Port(t, "port1")
    iDut1 := topo.AddInterface(atePort1.Name).WithPort(port1)
    iDut1.IPv4().WithAddress(atePort1.IPv4CIDR()).WithDefaultGateway(dut1Port1.IPv4)
    iDut1.IPv6().WithAddress(atePort1.IPv6CIDR()).WithDefaultGateway(dut1Port1.IPv6)
 
    // Configure ISIS on Port1, required for multihop iBGP.
    isisDut1 := iDut1.ISIS()
    isisDut1.WithLevelL2().
WithNetworkTypePointToPoint().
WithTERouterID(atePort1.IPv4).
WithLevelL1()

**Comment by greg-dennis** [comment]
This is fixed as of v0.1.17. You can now use `WithLevelL1L2()`
