### ISSUE TITLE
crafting VLAN tagged frames

### ISSUE THREAD

**Issue by singh-prem** [openconfig/ondatra#83]
I am looking to create a VLAN tagged GDP frame as below:
00 0A DA F0 F0 F0 00 AA 00 AA 00 AA 81 00 00 0A 60 07 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F 10 11 12 13 14 15 16 17 18 19 1A 1B 1C 1D 1E 1F 20 21 22 23 24 25 26 27 28 29 2A 2B 2C 2D 2E 2F 30 31 32 33 34 35 36 37 38 39 3A 3B 3C 3D 3E 3F

Currently https://github.com/openconfig/ondatra/blob/d81989ceab89c0959394fb2af750eda28e176533/headers.go#L42
Allows the add EtherType for an Ethernet Frame using WithEtherType, and https://github.com/openconfig/ondatra/blob/d81989ceab89c0959394fb2af750eda28e176533/headers.go#L82 allows to add a VLAN tag using WithVLANID.

WithEtherType is allowing to modify the EtherType in untagged Ethernet frame or TPID in tagged frame. But I am unable to modify the Type/Protocol-ID (0x6007 for GDP) following 802.1Q Header.
Refer: https://en.wikipedia.org/wiki/IEEE_802.1Q

Have tried following:
1. (results in an untagged GDP frame, second WithEtherType overwrites first)
	ethHeader := ondatra.NewEthernetHeader()
	ethHeader.WithSrcAddress(*gdp.SrcMAC)
	ethHeader.WithDstAddress(*gdp.DstMAC)
	ethHeader.WithEtherType(*ygot.Uint32(0x8100))
	ethHeader.WithVLANID(10)
	ethHeader.WithEtherType(*ygot.Uint32(0x6007))
2. (results in an untagged GDP frame, VLAN tag appears as payload)
	ethHeader := ondatra.NewEthernetHeader()
	ethHeader.WithSrcAddress(*gdp.SrcMAC)
	ethHeader.WithDstAddress(*gdp.DstMAC)
	ethHeader.WithEtherType(*ygot.Uint32(0x6007))
	ethHeader.WithVLANID(10)

**Comment by greg-dennis** [comment]
Notes and questions:

* Unrelated to your question, the expression `*ygot.Uint32(0x6007)` can just be `0x6007`.
* `WithEtherType` sets the ether type of the frame, so yes, if you call it multiple times, the second value will necessarily overwrite the first. That's to be expected.
* Can you provide documentation or a specification for a GDP frame?

**Comment by aaronmillisor** [comment]
GDP is a protocol that is proprietary to google, to my knowledge there is no spec. Perhaps @dplore can assist?

**Comment by dplore** [comment]
Here is an example of a test GDP packet without a VLAN: 

https://github.com/openconfig/featureprofiles/blob/main/feature/experimental/p4rt/otg_tests/google_discovery_protocol_packetout_test/google_discovery_protocol_packetout_test.go#L401

**Comment by greg-dennis** [comment]
Do those existing tests are using a p4rt client to send the gdp packets. We have a test where the Ixia/OTG needs to generate those packets?

**Comment by singh-prem** [comment]
> Do those existing tests are using a p4rt client to send the gdp packets. We have a test where the Ixia/OTG needs to generate those packets?

Here is an example of flow generation on IXIA for a GDP packet without vlan:
https://github.com/openconfig/featureprofiles/blob/2f3893811fd0d314f92f8e07eabbf7b5e2cea749/feature/experimental/p4rt/ate_tests/google_discovery_protocol_packetin_test/google_discovery_protocol_packetin_test.go#L465

**Comment by singh-prem** [comment]
sure @greg-dennis, will ask Keysight about how to get vlan tagged gdp frame on OTG.
