### ISSUE TITLE
Request to include openconfig-platform-psu.yang in gnmi

### ISSUE THREAD

**Issue by karthikeya-remilla** [openconfig/ondatra#86]
Hi,

could you please add openconfig-platform-psu.yang in the generate.sh file under ondatra/gnmi/  ?

Model: https://github.com/openconfig/public/blob/master/release/models/platform/openconfig-platform-psu.yang

**Comment by greg-dennis** [comment]
Yes, will do

**Comment by greg-dennis** [comment]
Fixed in https://github.com/openconfig/ondatra/releases/tag/v0.3.4
