### ISSUE TITLE
feat: UseGetForConfig for Nokia

### ISSUE THREAD

**Issue by cm-nokia** [openconfig/ondatra#88]
👋 hello!

it looks like we'll need to add nokia to the vendors that are using get for config gnmi option [here](https://github.com/openconfig/ondatra/blob/main/device.go#L90-L93). would somebody be able to make that change here pretty please?

**Comment by greg-dennis** [comment]
I'll take care of it

**Comment by greg-dennis** [comment]
This is fixed in https://github.com/openconfig/ondatra/releases/tag/v0.4.0. Next step is to require featureprofiles to use this version.
