### ISSUE TITLE
P4RT Client for ONDATRA

### ISSUE THREAD

**Issue by aaronmillisor** [openconfig/ondatra#9]
The OC "Feature Profile" set of tests includes a series of P4RT related cases. It appears that a stub of a p4rt client implementation is included [here](https://github.com/openconfig/ondatra/blob/main/internal/p4rt/p4rt.go), however a full implementation must be done before p4rt can be tested. Is work currently underway to develop this?

**Comment by greg-dennis** [comment]
What do you mean by a "full implementation"? In principle, any aspect of P4RT can be tested via the gRPC stub. If you want a higher-level API, we would need a design of what that ought to look like and example test cases that are difficult or cumbersome via raw gRPC.

**Comment by greg-dennis** [comment]
I will be writing more about this, but if we are going to provide a higher-level testing API for P4RT, we first require there exist higher-level _production_ API in Go. Once that exists, we can provide a more testing-oriented wrapper API.

**Comment by xw-g** [comment]
cc: @hariramnat

**Comment by greg-dennis** [comment]
Going to close because there is no P4RT production API today. If there were, we could building a testing API that wraps it.
