### ISSUE TITLE
Ondatra does not support capture

### ISSUE THREAD

**Issue by lyle-thompson-keysight** [openconfig/ondatra#92]
If I get a raw API object, then I can do capture, so some supported devices do support capture natively. But the APIs will vary between devices, and so are not guaranteed to be portable. Please add capture support to Ondatra.

**Comment by greg-dennis** [comment]
@lyle-thompson-keysight, could you clarify? The OTG API provides a `GetCapture` method, which is exposed through Ondatra as `ate.OTG().GetCapture()`. Is there another method on OTG that you would like us to expose?

**Comment by greg-dennis** [comment]
Closing for lack of detail
