### ISSUE TITLE
Errors while building and execute Ondatra's unit tests - ondatra 1.19 and 1.21 dependencies (FAIL	github.com/openconfig/ondatra [build failed])

### ISSUE THREAD

**Issue by anuuser1** [openconfig/ondatra#96]
Hi Team,

Tried the same procedure which is being mentioned with readme doc in gitbug. Got below dependency messages with go build and go test. Eventually tried with both 1.19 and 1.21  for go build and for go test but hitting below error. I have attached logs as well, please let me know if anything needs to be changes with the approach I have taken

root@anu-VirtualBox:/home/anu/ondatra# go build ./...
# github.com/golang/glog
/root/go/pkg/mod/github.com/golang/glog@v1.1.2/glog_file_other.go:27:6: abortProcess redeclared in this block
	/root/go/pkg/mod/github.com/golang/glog@v1.1.2/glog_file_linux.go:33:6: other declaration of abortProcess
note: module requires Go 1.19
# google.golang.org/grpc
/root/go/pkg/mod/google.golang.org/grpc@v1.59.0/server.go:2082:14: undefined: atomic.Int64
note: module requires Go 1.19

root@anu-VirtualBox:/home/anu/ondatra# go test -testbed=testbed.textproto -config=config.yaml -run=$RUN_THIS_TEST_CASE
# github.com/openconfig/ondatra/gnmi/oc
gnmi/oc/enum.go:88:2: imported and not used: "encoding/json"
gnmi/oc/enum.go:89:2: imported and not used: "fmt"
gnmi/oc/enum.go:90:2: imported and not used: "reflect"
gnmi/oc/enum.go:93:2: imported and not used: "github.com/openconfig/goyang/pkg/yang"
gnmi/oc/enum.go:94:2: imported and not used: "github.com/openconfig/ygot/ytypes"
gnmi/oc/enum_map.go:88:2: imported and not used: "encoding/json"
gnmi/oc/enum_map.go:89:2: imported and not used: "fmt"
gnmi/oc/enum_map.go:93:2: imported and not used: "github.com/openconfig/goyang/pkg/yang"
gnmi/oc/enum_map.go:94:2: imported and not used: "github.com/openconfig/ygot/ytypes"
gnmi/oc/schema.go:88:2: imported and not used: "encoding/json"
gnmi/oc/schema.go:88:2: too many errors
note: module requires Go 1.21
# github.com/openconfig/ondatra/gnmi/otg
gnmi/otg/enum.go:25:2: imported and not used: "encoding/json"
gnmi/otg/enum.go:26:2: imported and not used: "fmt"
gnmi/otg/enum.go:27:2: imported and not used: "reflect"
gnmi/otg/enum.go:30:2: imported and not used: "github.com/openconfig/goyang/pkg/yang"
gnmi/otg/enum.go:31:2: imported and not used: "github.com/openconfig/ygot/ytypes"
gnmi/otg/enum_map.go:25:2: imported and not used: "encoding/json"
gnmi/otg/enum_map.go:26:2: imported and not used: "fmt"

gnmi/otg/enum_map.go:30:2: imported and not used: "github.com/openconfig/goyang/pkg/yang"
gnmi/otg/enum_map.go:31:2: imported and not used: "github.com/openconfig/ygot/ytypes"
gnmi/otg/schema.go:25:2: imported and not used: "encoding/json"
gnmi/otg/schema.go:25:2: too many errors
note: module requires Go 1.21

Regards,
Anu

[Ondatra_logs.txt](https://github.com/openconfig/ondatra/files/13938858/Ondatra_logs.txt)

**Comment by greg-dennis** [comment]
In the logs, the `go generate` command failed because protoc is not installed. Can you please try `sudo apt install -y protobuf-compiler` and retry?

**Comment by greg-dennis** [comment]
I'm going to assume this fixed he issue. Reopen if it did not.
