### ISSUE TITLE
go generate ./... and go build ./... errors

### ISSUE THREAD

**Issue by 6303210121** [openconfig/ondatra#98]
when I tried to run go generate ./... and go build ./... these are the errors/issues I am facing help me out. I am using go 1.21 version

root@avi-virtualbox:~/ondatra$ go generate ./...
generate.go:18: running "./gnmi/generate.sh": exit status 1

root@avi-virtualbox:~/ondatra$ go build ./...
# github.com/openconfig/ondatra/binding
binding/binding.go:182:57: undefined: gosnappi.GosnappiApi
binding/abstract.go:168:76: undefined: gosnappi.GosnappiApi

**Comment by greg-dennis** [comment]
As noted in https://github.com/openconfig/ondatra/issues/98, please don't continue onto a subsequent step if the current step failed. In this case, `go generate` failed, so please don't continue onto `go build`. Please do a fresh checkout and run `go generate` and paste the full log here.

**Comment by greg-dennis** [comment]
Closing for lack of detail
